spring.config.import=optional:file:.env[.properties]

spring.application.name=udemy

server.port=${PORT}

spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
