spring.config.import=optional:file:.env[.properties]

spring.application.name=udemy

server.port=${PORT}

spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION_TIME}

spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enabled=true
spring.mail.properties.mail.smtp.starttls.required=true

password.reset.link=http://localhost:3000/reset-password?code=